"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArrowRight, Check, ChevronRight, Code2, Dumbbell, Github, Heart, Instagram, LockKeyhole, PartyPopper, Sparkles, Terminal as TerminalIcon, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const bootLines = ["Inicializando sistema...", "Carregando módulos...", "Instagram API conectada ✓", "Módulo de programação carregado ✓", "Módulo fitness carregado ✓", "Procurando usuária...", "Usuária encontrada.", "Nome: Heryka", "Iniciando análise..."];
const scans = ["Programação detectada... ✓", "Academia detectada... ✓", "Instagram detectado... ✓", "Personalidade interessante... ✓", "Nível de perigo... analisando..."];
const steps = ["BOOT", "SCAN", "MATCH", "REPO", "WORKOUT", "TERMINAL", "QUIZ", "RESULT"];

export default function HerykaExperience() {
  const [stage, setStage] = useState(0);
  const [bootCount, setBootCount] = useState(0);
  const [progress, setProgress] = useState(0);
  const [easterClicks, setEasterClicks] = useState(0);
  const [toast, setToast] = useState("");

  useEffect(() => {
    if (stage !== 0 || bootCount >= bootLines.length) return;
    const id = setTimeout(() => setBootCount(v => v + 1), bootCount === 0 ? 450 : 340);
    return () => clearTimeout(id);
  }, [bootCount, stage]);
  useEffect(() => {
    if (stage !== 1) return;
    setProgress(0);
    const id = setInterval(() => setProgress(v => v >= 100 ? (clearInterval(id), 100) : Math.min(100, v + 2)), 42);
    return () => clearInterval(id);
  }, [stage]);
  const triggerEgg = () => {
    const n = easterClicks + 1; setEasterClicks(n);
    if (n === 5) { setToast("Heryka, você está tentando quebrar o sistema?"); setTimeout(() => setToast(""), 3500); }
  };

  return (
    <main className="relative min-h-screen overflow-hidden bg-[#060609]">
      <Background onSecret={triggerEgg} />
      <Topbar stage={stage} />
      <AnimatePresence mode="wait">
        <motion.div key={stage} initial={{ opacity: 0, y: 18, filter: "blur(8px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} exit={{ opacity: 0, y: -16, filter: "blur(7px)" }} transition={{ duration: .5 }} className="relative z-10">
          {stage === 0 && <Boot lines={bootLines.slice(0, bootCount)} ready={bootCount === bootLines.length} next={() => setStage(1)} />}
          {stage === 1 && <Scan progress={progress} next={() => setStage(2)} />}
          {stage === 2 && <Compatibility next={() => setStage(3)} />}
          {stage === 3 && <Repository next={() => setStage(4)} />}
          {stage === 4 && <Workout next={() => setStage(5)} />}
          {stage === 5 && <InteractiveTerminal next={() => setStage(6)} />}
          {stage === 6 && <Quiz next={() => setStage(7)} />}
          {stage === 7 && <Decision />}
        </motion.div>
      </AnimatePresence>
      <AnimatePresence>{toast && <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="fixed bottom-5 left-1/2 z-50 w-[calc(100%-2rem)] max-w-md -translate-x-1/2 rounded-xl border border-pink-400/30 bg-[#15101c]/95 p-4 text-center text-sm text-pink-200 shadow-[0_0_30px_rgba(255,70,190,.2)] mono">{toast}</motion.div>}</AnimatePresence>
    </main>
  );
}

function Background({onSecret}:{onSecret:()=>void}) {
  return <div className="pointer-events-none fixed inset-0 z-0 overflow-hidden">
    <div className="absolute inset-0 grid-bg"/><div className="noise absolute inset-0 opacity-20"/>
    <div className="absolute -left-32 top-10 h-80 w-80 rounded-full bg-violet-700/20 blur-[100px]"/><div className="absolute -right-24 bottom-10 h-72 w-72 rounded-full bg-cyan-500/10 blur-[100px]"/>
    <div className="float-code absolute left-[5%] top-[18%] text-xs text-violet-300/[.09] mono">const heryka = await findSpecialPerson();</div>
    <div className="float-code absolute right-[4%] top-[34%] text-4xl text-cyan-300/[.06] mono">{"{ }"}</div>
    <div className="absolute bottom-[14%] left-[3%] rotate-[-12deg] text-violet-300/[.07]"><Dumbbell size={92}/></div>
    <div className="absolute right-[9%] top-[12%] text-pink-300/[.07]"><Code2 size={74}/></div>
    <button aria-label="easter egg" onClick={onSecret} className="pointer-events-auto absolute bottom-2 right-2 h-10 w-10 opacity-0" />
  </div>;
}

function Topbar({stage}:{stage:number}) { return <header className="fixed inset-x-0 top-0 z-30 border-b border-white/[.06] bg-[#07070a]/70 backdrop-blur-xl"><div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-4"><div className="flex items-center gap-2 text-sm font-bold tracking-wider"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]"/>HERYKA<span className="text-violet-400">.exe</span></div><div className="hidden items-center gap-2 sm:flex">{steps.map((s,i)=><span key={s} className={`h-1 rounded-full transition-all ${i===stage?'w-8 bg-violet-400':'w-3 '+(i<stage?'bg-violet-800':'bg-white/10')}`}/>)}</div><span className="text-[10px] tracking-[.2em] text-white/35 mono">{String(stage+1).padStart(2,"0")}/08</span></div></header> }

const Shell = ({eyebrow,title,children}:{eyebrow:string,title:string,children:React.ReactNode}) => <section className="mx-auto flex min-h-screen w-full max-w-5xl flex-col justify-center px-4 pb-14 pt-24 sm:px-8"><div className="mb-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.25em] text-violet-400 mono"><span className="h-px w-8 bg-violet-500"/>{eyebrow}</div><h1 className="mb-8 max-w-3xl text-3xl font-bold leading-tight tracking-tight sm:text-5xl">{title}</h1>{children}</section>;
const Next = ({onClick,label="CONTINUAR"}:{onClick:()=>void,label?:string}) => <motion.button whileTap={{scale:.97}} onClick={onClick} className="neon-button mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-6 py-4 text-sm font-bold tracking-[.12em] sm:w-auto">{label}<ArrowRight size={17}/></motion.button>;

function Boot({lines,ready,next}:{lines:string[],ready:boolean,next:()=>void}) { return <Shell eyebrow="secure boot / private access" title=""><div className="glass scanline relative overflow-hidden rounded-2xl"><div className="flex h-11 items-center gap-2 border-b border-white/10 px-4"><i className="h-3 w-3 rounded-full bg-[#ff5f57]"/><i className="h-3 w-3 rounded-full bg-[#febc2e]"/><i className="h-3 w-3 rounded-full bg-[#28c840]"/><span className="ml-2 text-[10px] text-white/30 mono">heryka-system — zsh</span></div><div className="min-h-[390px] p-5 sm:p-8 mono">{lines.map((l,i)=><motion.p initial={{opacity:0,x:-5}} animate={{opacity:1,x:0}} key={l} className={`mb-3 text-xs sm:text-sm ${l.includes("✓")?'text-emerald-300':l==='Nome: Heryka'?'text-pink-300':'text-white/60'}`}><span className="mr-2 text-violet-400">›</span>{l}</motion.p>)}{!ready&&<span className="cursor inline-block h-4 w-2 bg-violet-400"/>}{ready&&<motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="mt-8 border-l-2 border-violet-500 pl-5"><h2 className="bg-gradient-to-r from-white via-violet-200 to-cyan-300 bg-clip-text text-4xl font-black text-transparent sm:text-6xl">HERYKA.exe</h2><p className="mt-3 max-w-lg text-xs leading-6 text-white/45">Sistema desenvolvido exclusivamente para uma única usuária.</p></motion.div>}</div></div>{ready&&<Next onClick={next} label="INICIAR SISTEMA"/>}</Shell> }

function Scan({progress,next}:{progress:number,next:()=>void}) { const visible=Math.min(scans.length,Math.ceil(progress/18)); return <Shell eyebrow="profile scanner" title="ANALISANDO PERFIL..."><div className="glass rounded-2xl p-5 sm:p-8"><div className="mb-3 flex items-end justify-between"><span className="text-xs text-white/40 mono">SCAN_ID: HRK-001</span><strong className="text-3xl text-cyan-300 mono">{progress}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><motion.div className="h-full bg-gradient-to-r from-violet-600 via-fuchsia-500 to-cyan-400 shadow-[0_0_18px_#8b5cf6]" animate={{width:`${progress}%`}}/></div><div className="mt-8 space-y-4">{scans.slice(0,visible).map((s,i)=><motion.div initial={{opacity:0,x:-10}} animate={{opacity:1,x:0}} key={s} className="flex items-center gap-3 text-sm text-white/65 mono"><Check size={16} className={i<4?"text-emerald-400":"text-amber-400"}/>{s}</motion.div>)}</div></div>{progress===100&&<motion.div initial={{opacity:0}} animate={{opacity:1}}><p className="my-7 flex items-center gap-3 text-sm font-bold tracking-[.2em] text-emerald-300 mono"><Check/>ANÁLISE CONCLUÍDA</p><div className="grid gap-3 sm:grid-cols-2"><Metric icon={<Code2/>} label="PROGRAMAÇÃO" value="ATIVA"/><Metric icon={<Dumbbell/>} label="ACADEMIA" value="MODO TREINO ATIVADO"/><Metric icon={<Instagram/>} label="ORIGEM DA CONEXÃO" value="INSTAGRAM"/><Metric icon={<Zap/>} label="NÍVEL DE INTERESSE" value="ALTO ⚠️"/><div className="glass sm:col-span-2 rounded-xl p-5"><p className="text-xs text-white/40 mono">CHANCE DE HERYKA SER INTERESSANTE DEMAIS</p><p className="mt-2 text-4xl font-bold text-pink-300">99.9%</p><small className="text-white/30">Margem de erro: provavelmente 0%.</small></div></div><Next onClick={next}/></motion.div>}</Shell> }
function Metric({icon,label,value}:{icon:React.ReactNode,label:string,value:string}) { return <div className="glass flex items-center gap-4 rounded-xl p-5"><span className="text-violet-400">{icon}</span><div><p className="text-[10px] tracking-wider text-white/35 mono">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div></div> }

function Compatibility({next}:{next:()=>void}) { const rows=[["Programação",100],["Academia",94],["Conversas",97],["Curiosidade",100],["Chance deste site ser para impressionar Heryka",100]] as [string,number][]; return <Shell eyebrow="neural match engine" title="COMPATIBILITY SYSTEM v1.0"><div className="glass rounded-2xl p-5 sm:p-8"><div className="space-y-6">{rows.map(([label,n],i)=><div key={label}><div className="mb-2 flex justify-between gap-5 text-xs mono"><span className="text-white/60">{label}</span><span className="text-cyan-300">{n}%</span></div><div className="h-2 rounded bg-white/5"><motion.div initial={{width:0}} animate={{width:`${n}%`}} transition={{duration:1,delay:i*.15}} className="h-full rounded bg-gradient-to-r from-violet-600 to-cyan-400"/></div></div>)}</div><div className="mt-9 border-t border-white/10 pt-7"><p className="text-xs text-white/40 mono">COMPATIBILIDADE GERAL</p><p className="mt-1 text-5xl font-black">98.7<span className="text-violet-400">%</span></p></div></div><div className="glitch mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-4 text-sm text-amber-100/75 mono">⚠ Dados insuficientes.<br/><span className="text-white/45">Os 1.3% restantes precisam ser analisados presencialmente.</span></div><Next onClick={next}/></Shell> }

function Repository({next}:{next:()=>void}) { const commits=[["001","feat: Heryka apareceu no Instagram"],["002","feat: primeira conversa iniciada"],["003","update: interesse aumentando"],["004","fix: tentativa de parecer menos interessado"],["005","feat: desenvolvedor decidiu criar um site para Heryka"],["???","next feature: encontro presencial?"]]; return <Shell eyebrow="source control" title="Repository: heryka-connection"><div className="glass overflow-hidden rounded-2xl"><div className="grid grid-cols-2 gap-5 border-b border-white/10 p-5 text-xs sm:grid-cols-4 sm:p-7 mono">{[["STATUS","Em desenvolvimento"],["BRANCH","main"],["ORIGIN","Instagram"],["CONTRIBUTORS","2"]].map(([a,b])=><div key={a}><p className="text-white/30">{a}</p><p className="mt-1 text-white/75">{b}</p></div>)}</div><div className="p-5 sm:p-8">{commits.map(([id,msg],i)=><motion.div initial={{opacity:0,x:-12}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.08}} key={id+msg} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 mt-1 h-3 w-3 shrink-0 rounded-full border-2 border-violet-400 bg-[#0c0b12] shadow-[0_0_10px_#8b5cf6]"/>{i<commits.length-1&&<div className="absolute left-[5px] top-4 h-full w-px bg-white/10"/>}<div><span className="text-[10px] text-violet-400 mono">commit {id}</span><p className="mt-1 text-sm text-white/65 mono">{msg}</p>{id==="004"&&<p className="mt-2 text-xs text-red-400 mono">ERROR: fix unsuccessful</p>}</div></motion.div>)}</div></div><Next onClick={next}/></Shell> }

function Workout({next}:{next:()=>void}) { const items=[{n:"01",t:"AQUECIMENTO",body:"3 séries de conversa\n12 mensagens por série",meta:"Descanso: enquanto a outra pessoa responde"},{n:"02",t:"CARDIO",body:"Fugir do sentimento",meta:"Falha detectada."},{n:"03",t:"TREINO DE FORÇA",body:"4x manter a postura depois de perceber que está gostando",meta:"Dificuldade: EXTREMA"},{n:"04",t:"EXERCÍCIO RECOMENDADO",body:"Sair comigo",meta:"Séries indefinidas · Repetições podem aumentar dependendo do resultado."}]; return <Shell eyebrow="training protocol" title="HERYKA WORKOUT PLAN"><div className="mb-5 flex items-center justify-between rounded-xl border border-emerald-400/20 bg-emerald-400/[.05] p-4 text-xs mono"><span className="flex items-center gap-2 text-emerald-300"><Activity size={16}/>PLAN ACTIVE</span><span className="text-white/30">WEEK 01</span></div><div className="grid gap-4 sm:grid-cols-2">{items.map((x,i)=><motion.article whileHover={{y:-4}} key={x.n} className="glass relative overflow-hidden rounded-2xl p-6"><span className="absolute right-4 top-2 text-6xl font-black text-white/[.025] mono">{x.n}</span><Dumbbell className="mb-8 text-violet-400"/><p className="text-[10px] tracking-[.2em] text-white/35 mono">{x.t}</p><p className="mt-3 whitespace-pre-line text-lg font-semibold leading-7">{x.body}</p><p className={`mt-5 text-xs mono ${i===1?'text-red-400':i===3?'text-pink-300':'text-cyan-300'}`}>{x.meta}</p></motion.article>)}</div><Next onClick={next}/></Shell> }

function InteractiveTerminal({next}:{next:()=>void}) { const answers:Record<string,string>={whoami:"Heryka.\nUsuária principal deste sistema.",status:"Conexão ativa.\nInteresse detectado.\nSistema funcionando normalmente.",why:"Porque aparentemente uma conversa no Instagram foi suficiente para o desenvolvedor começar a inventar moda.",next_step:"Executando...\n\nResultado encontrado:\nEncontrar Heryka pessoalmente.",developer_status:"Tentando parecer normal.\n\nResultado: falhou."}; const [history,setHistory]=useState<{cmd:string,out:string}[]>([]); return <Shell eyebrow="interactive command line" title="TERMINAL INTERATIVO"><div className="glass scanline relative overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><span className="flex items-center gap-2 text-xs text-white/40 mono"><TerminalIcon size={15}/>heryka@system:~$</span><LockKeyhole size={14} className="text-emerald-400"/></div><div className="min-h-[330px] p-5 mono sm:p-7"><div className="mb-6 flex flex-wrap gap-2">{Object.keys(answers).map(cmd=><button onClick={()=>setHistory(h=>[...h,{cmd,out:answers[cmd]}])} key={cmd} className="rounded-lg border border-violet-400/20 bg-violet-400/[.07] px-3 py-2 text-xs text-violet-200 transition hover:bg-violet-400/15">{cmd}</button>)}</div>{history.length===0&&<p className="text-xs text-white/30">Selecione um comando para executar.</p>}{history.slice(-3).map((h,i)=><motion.div initial={{opacity:0}} animate={{opacity:1}} key={i+h.cmd} className="mb-5 text-xs leading-6"><p><span className="text-emerald-400">heryka@system:~$</span> <span className="text-white/80">{h.cmd}</span></p><p className="whitespace-pre-line text-white/45">{h.out}</p></motion.div>)}</div></div><Next onClick={next} label="ABRIR QUESTIONÁRIO"/></Shell> }

function Quiz({next}:{next:()=>void}) { const questions=[{q:"Escolha sua linguagem:",opts:["JavaScript","TypeScript","Python","Depende do projeto"],response:(x:string)=>x==="TypeScript"?"Resposta aprovada pelo sistema.":"Sistema aceita sua decisão... por enquanto."},{q:"Você prefere:",opts:["Academia","Programar","Sair","Todas as anteriores"],response:(x:string)=>x==="Todas as anteriores"?"⚠ RESPOSTA PERIGOSA DETECTADA.":"Preferência registrada com sucesso."},{q:"Se você pudesse escolher agora:",opts:["Treinar comigo","Programar alguma coisa comigo","Sair comigo","Por que isso está parecendo um convite?"],response:(x:string)=>x.startsWith("Por que")?"Porque talvez seja.":"Interessante... salvando resposta."}]; const [index,setIndex]=useState(0); const [reply,setReply]=useState(""); const choose=(o:string)=>setReply(questions[index].response(o)); const advance=()=>{setReply("");setIndex(i=>i+1)}; const done=index>=questions.length; return <Shell eyebrow="behavioral assessment" title="QUIZ INTERATIVO">{!done?<div className="glass rounded-2xl p-5 sm:p-8"><div className="mb-8 flex items-center justify-between"><span className="text-xs text-white/35 mono">PERGUNTA {index+1}/03</span><div className="h-1 w-24 overflow-hidden rounded bg-white/10"><div style={{width:`${((index+1)/3)*100}%`}} className="h-full bg-violet-500"/></div></div><h2 className="mb-6 text-xl font-semibold sm:text-2xl">{questions[index].q}</h2><div className="grid gap-3 sm:grid-cols-2">{questions[index].opts.map((o,i)=><button key={o} onClick={()=>choose(o)} className="group flex items-center justify-between rounded-xl border border-white/10 bg-white/[.03] p-4 text-left text-sm transition hover:border-violet-400/50 hover:bg-violet-400/[.08]"><span><i className="mr-3 not-italic text-violet-400 mono">{String.fromCharCode(65+i)}</i>{o}</span><ChevronRight size={16} className="text-white/20 transition group-hover:translate-x-1 group-hover:text-violet-300"/></button>)}</div><AnimatePresence mode="wait">{reply&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-6 rounded-xl border border-cyan-300/20 bg-cyan-300/[.05] p-4 text-sm text-cyan-100 mono">{reply}<button onClick={advance} className="mt-4 flex items-center gap-2 text-xs font-bold text-white">PRÓXIMA <ArrowRight size={14}/></button></motion.div>}</AnimatePresence></div>:<div className="glass rounded-2xl p-8 text-center"><Check className="mx-auto mb-4 text-emerald-400" size={36}/><h2 className="text-2xl font-bold">Respostas armazenadas.</h2><p className="mt-2 text-sm text-white/40">Nenhum dado foi enviado para a NASA. Ainda.</p></div>}{done&&<Next onClick={next} label="PROCESSAR RESULTADO"/>}</Shell> }

function Decision() { const [result,setResult]=useState<"yes"|"review"|null>(null); const particles=useMemo(()=>Array.from({length:36},(_,i)=>({id:i,left:(i*37)%100,delay:(i%8)*.07,color:["#a78bfa","#22d3ee","#f472b6","#facc15"][i%4]})),[]); return <Shell eyebrow="final output" title=""><div className="text-center"><div className="mb-8 space-y-2 text-xs text-white/35 mono"><p>Processando todas as informações...</p><p>Analisando respostas...</p><p>Consultando banco de dados...</p><p className="text-emerald-300">Resultado encontrado. ✓</p></div><Sparkles className="mx-auto mb-5 text-pink-300"/><h1 className="mx-auto max-w-3xl text-4xl font-black leading-tight sm:text-6xl">Heryka,<br/><span className="bg-gradient-to-r from-violet-300 via-pink-300 to-cyan-300 bg-clip-text text-transparent">aparentemente precisamos coletar mais dados.</span></h1><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-white/45">E existe apenas uma maneira cientificamente comprovada de fazer isso.</p><div className="glass mx-auto mt-9 max-w-2xl rounded-3xl p-6 sm:p-10"><Heart className="mx-auto mb-5 text-pink-400" fill="currentColor"/><h2 className="text-2xl font-bold sm:text-3xl">Você aceitaria sair comigo?</h2>{!result&&<div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={()=>setResult("yes")} className="neon-button rounded-xl bg-gradient-to-r from-pink-500 to-violet-600 p-4 text-sm font-bold">SIM</button><button onClick={()=>setResult("review")} className="rounded-xl border border-white/10 bg-white/[.04] p-4 text-xs font-bold transition hover:bg-white/[.08]">VOU ANALISAR O PULL REQUEST</button></div>}{result&&<motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} className="mt-7">{result==="yes"?<><PartyPopper className="mx-auto text-yellow-300" size={34}/><p className="mt-4 text-xl font-bold text-emerald-300 mono">STATUS: APROVADO ✓</p><p className="mt-2 text-white/60">Deploy realizado com sucesso.</p><p className="mt-1 text-sm text-pink-200">Agora só falta definir a data.</p></>:<><Github className="mx-auto text-violet-300"/><p className="mt-4 font-bold">Pull Request enviado para revisão.</p><p className="mt-2 text-sm leading-6 text-white/45">O desenvolvedor aguarda pacientemente.<br/>Ou pelo menos vai tentar.</p></>}</motion.div>}</div><p className="mt-8 text-[10px] text-white/20 mono">// TODO: descobrir se Heryka gostou disso</p></div>{result==="yes"&&<div className="pointer-events-none fixed inset-0 z-50 overflow-hidden">{particles.map(p=><motion.i key={p.id} initial={{top:"-5%",left:`${p.left}%`,rotate:0,opacity:1}} animate={{top:"105%",rotate:720,opacity:[1,1,0]}} transition={{duration:2.8+(p.id%5)*.2,delay:p.delay,ease:"easeIn"}} style={{background:p.color}} className="absolute h-3 w-2 rounded-sm"/>)}</div>}</Shell> }
